2018-12-25 22:45:14,913 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 22:45:26,694 ERROR: Exception on /get_specialities [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: get_specialities() missing 1 required positional argument: 'request'
2018-12-25 22:51:58,576 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 22:52:04,502 ERROR: Exception on /get_specialities [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: get_specialities() missing 1 required positional argument: 'request'
2018-12-25 22:52:33,498 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 22:52:35,681 ERROR: Exception on /get_specialities [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 16, in get_specialities
    form = (request.POST)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'POST'
2018-12-25 22:53:19,233 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 22:53:21,959 ERROR: Exception on /get_specialities [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 16, in get_specialities
    form = (request.POST)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'POST'
2018-12-25 22:54:20,065 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 22:54:32,883 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 22:55:22,386 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 22:56:28,689 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:05:16,483 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:05:20,705 ERROR: Exception on /get_specialities [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 18, in get_specialities
    form.specialities.choices = data
AttributeError: 'SpecialityForm' object has no attribute 'specialities'
2018-12-25 23:05:39,469 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:08:59,644 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:28:05,882 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:30:50,150 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:31:38,190 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:35:32,176 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-25 23:38:20,248 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:05:45,221 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:13:18,774 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:13:27,191 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:17:16,730 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:20:24,245 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:21:33,683 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:23:37,006 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:46:30,373 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:51:07,813 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 00:52:54,608 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
