2018-12-26 01:50:03,384 ERROR: Exception on /get_specialities/ [POST] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 33, in get_specialities
    return render_template('specialities.html', title='Specialities', form=form, selection=16)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\templates\specialities.html", line 9, in template
    <option value="{{ choice }}"{% if selection is choice  %} selected="selected" {% endif %}>{{ choice }}</option>
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 543, in _generate
    optimized=self.optimized)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 82, in generate
    generator.visit(node)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 799, in visit_Template
    self.blockvisit(block.body, block_frame)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 1122, in visit_For
    self.blockvisit(node.body, loop_frame)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 1157, in visit_If
    self.visit(node.test, if_frame)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 70, in new_func
    return f(self, node, frame, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 1607, in visit_Test
    self.fail('no test named %r' % node.name, node.lineno)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no test named 'choice'
2018-12-26 01:50:47,604 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 01:51:13,716 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 01:54:06,415 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 01:54:34,178 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 01:55:47,880 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 01:58:00,912 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 02:01:29,668 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 02:02:13,214 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 02:02:21,045 ERROR: Exception on /get_specialities/ [POST] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 27, in get_specialities
    return render_template(option, title='Specialities', form=form, selection=choice)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 872, in get_or_select_template
    return self.select_template(template_name_or_list, parent, globals)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 845, in select_template
    raise TemplatesNotFound(message=u'Tried to select from an empty list '
jinja2.exceptions.TemplatesNotFound: Tried to select from an empty list of templates.
2018-12-26 02:03:29,775 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-26 02:03:33,405 ERROR: Exception on /get_specialities/ [POST] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 28, in get_specialities
    f.write(option)
TypeError: write() argument must be str, not None
2018-12-26 02:04:27,952 INFO: Abithelper startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
