2018-12-20 22:42:23,614 INFO: Microblog startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:26]
2018-12-20 22:42:33,889 INFO: Microblog startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:26]
2018-12-20 22:42:38,251 ERROR: Exception on / [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 10, in index
    return render_template('index.html', title='Home')
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 133, in render_template
    ctx.app.update_template_context(context)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 792, in update_template_context
    context.update(func())
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\login_manager.py", line 317, in reload_user
    "No user_loader has been installed for this "
Exception: No user_loader has been installed for this LoginManager. Refer tohttps://flask-login.readthedocs.io/en/latest/#how-it-works for more info.
2018-12-20 22:44:17,655 INFO: Microblog startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:26]
2018-12-20 22:44:21,836 ERROR: Exception on / [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 9, in index
    return render_template('index.html', title='Home')
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 133, in render_template
    ctx.app.update_template_context(context)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 792, in update_template_context
    context.update(func())
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\login_manager.py", line 317, in reload_user
    "No user_loader has been installed for this "
Exception: No user_loader has been installed for this LoginManager. Refer tohttps://flask-login.readthedocs.io/en/latest/#how-it-works for more info.
2018-12-20 22:45:59,889 INFO: Microblog startup [in C:\Users\Admin\Desktop\1\py\AbitHelper\app\__init__.py:24]
2018-12-20 22:46:09,788 ERROR: Exception on / [GET] [in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Desktop\1\py\AbitHelper\app\routes.py", line 9, in index
    return render_template('index.html', title='Home')
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
